### PR TITLE
New version of Alfred-Cheat

### PR DESCRIPTION
**Pull request by odapg**
Hi Wayne,
Here is the pull request for my new version of Alfred-Workflow.
Best,
Olivier.

### CODE REVIEW

**Comment by wx-Yao** [comment]
Hi Olivier @odapg, thanks very much first for your contribution and your interest to invest in this project. I like your ideas, especially the "open in editor" and the parsing rule. The "preview in HTML" seems ... good but I think they might be useful with long comments and complicated commands right? Anyways it's good to have that. Thanks.

But to merge your feature, could you please separate your commit to small commits that contain different features? it's easier to do the review and I can see possible improvements in the code but couldn't give comments because I'm not sure what it is for. All you change now is in one single commit, which is a bit of anti-engineering.

So here's how I'm gonna do to integrate your idea into a new release:

Option 1: Separate your commit by features. I can do a very quick review of each one, and merge fast. When all features are merged, I'll release 2.0 version ASAP. Yeah they're worth a version bump.

Option 2: I'll take time to read your code, understand your logic and implement on my own again. I'll quote your name in the README and the code comment of course no worries. But you might not appear in the commit history. 

Thanks again :) Let me know if it works out for you.

Wayne

**Comment by odapg** [comment]
Hi Wayne,
Sure, I will try to make separate commits. Give me a few days :-)
Concerning the HTML feature, I use it to have a global view of the hotkeys of an app; I suppose it is a bit different if you mainly use cheatsheets for unix commands...

**Comment by wx-Yao** [comment]
Yeah I mainly use for unix command. But sure the HTML preview is an awesome idea. Even linux commands need a way sometimes to e.g., see detailed description. 

And cool thanks for your effort! take your time!

**Comment by odapg** [comment]
Hi, I made six different branches to the workflow which are actually incremental (not at all independent — for instance the Quicklook preview heavily depends on the parsing rule of course). The HTML preview corresponds to alfred-cheat-commit5. 

I am pulling the requests, let me know what you think!

**Comment by wx-Yao** [comment]
Closing this one as the review is on other branches. Thanks for your contribution.

**Pull request closed without merging**
