### PR TITLE
Updates options.py 

### PR DESCRIPTION
**Pull request by odapg**
This is my commit #2

Adds the possibility to open the cheatsheet file in a text editor by holding command when selecting an item.
One should add a "open file" command to the workflow, with "command" action modifier

### CODE REVIEW

**Review by wayneyaoo — COMMENTED** [review]
This PR wanna address the "open in editor" feature right? looks cool but it seems you are branching based on previous PR commit lol ... if i merge the previous PR #11, it might conflict with this one. Will you be able to resolve it?

**Comment by odapg** [comment]
Yes, these commits are incremental. I am not completely sure how to do it differently (and I am open to advice if you have ideas on the subject). If needed, I will resolve the conflicts after #PR11 is merged.

**Comment by wx-Yao** [comment]
:) you don't have to do different PR actually. When i was talking about "separating commits", it means literally "commit your code multiple times by feature and create one single PR" so that if there's any problem in one of the commits I can do cherry-pick to merge the rest.

You seem to PR in style like "commit once, make PR, checkout a new branch, commit again, make another PR ...". In this manner each newly created branch will contain commits in the last branch. That's why we have such incremented PR now.

If you want to submit PRs by features, you need to checkout *back* to master every time before you create a new branch. i.e., "commit once, make PR, check out master, create a branch, commit again, make PR..." You need to make sure features are independent so that PRs are independent.

But anyway it's fine. Let's do it in the most accumulated branch, so that you don't have to resolve conflict. Make sure all your changes are made to #16 . the branch `odapg:alfred-cheat-commit6`. I'll only merge that one, which contains all.

**Comment by wx-Yao** [comment]
close as discussed in #16

**Pull request closed without merging**
